#' @include DIC.R
NULL

#' @title Function \code{DIC}
#' @description Get the deviance information criterion (DIC) of a chain or list of chains, along with the 
#' effective and actual numbers of parameters.
#' @export
#' @return DIC
#' @param chain_list a \code{Chain} object or list of \code{Chain} objects generated by \code{fbseq()}
DIC = function(chain_list){
  if(class(chain_list) == "Chain") chain_list = list(chain_list)
  stopifnot(length(chain_list) > 0)
  G = chain_list[[1]]@G
  N = chain_list[[1]]@N
  ll = mean(sapply(chain_list, function(x) x@loglikPostMean))
  Dbar = -2*ll
  n = sum(sapply(chain_list, function(ch) ch@iterations * ch@thin))
  m = rowSums(sapply(chain_list, function(ch) flatten_post(ch) * ch@iterations * ch@thin))/n
  h = colMeans(do.call(rbind, lapply(chain_list, function(ch) ch@h)))
  h = matrix(rep(h, each = G), ncol = N)
  epsilon = matrix(m[grepl("epsilon_", names(m))], nrow = G)
  beta = matrix(m[grepl("beta_", names(m))], nrow = G)
  X = Scenario(chain_list[[1]])@design
  Xbeta = t(X %*% t(beta))
  loglambda = h + epsilon + Xbeta
  y = Scenario(chain_list[[1]])@counts
  ll2 = sum(-exp(loglambda) + y * loglambda - lgamma(y + 1))
  DthetaBar = -2*ll2
  pD = Dbar - DthetaBar
  DIC = Dbar + pD
  numParms = N*G + G + 2 + (G + 2)*ncol(X) + G*sum(chain_list[[1]]@priors > 0)
  c(DIC = DIC, parms = numParms, effectiveParms = pD)
}
